# Generated by Django 4.2.2 on 2023-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialViajes',
            fields=[
                ('id_Historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('destino', models.CharField(max_length=100)),
                ('pasajeros', models.IntegerField()),
            ],
        ),
    ]
