# Generated by Django 4.2.2 on 2023-06-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_conductor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='nombre',
        ),
    ]
