# Generated by Django 4.2.2 on 2023-06-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_email_conductor_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='asientos',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
