# Generated by Django 4.2.2 on 2023-06-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conductor_asientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='Disponible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipoauto',
            field=models.CharField(default=1, max_length=30, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
