# Generated by Django 4.2.2 on 2023-06-23 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_conductor_disponible_conductor_tipoauto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialViajes',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellido',
            field=models.CharField(default='apellido', max_length=20, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='asientos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='conductor',
            field=models.ForeignKey(default='A1onsoo', on_delete=django.db.models.deletion.CASCADE, to='app.conductor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='nombre', max_length=20, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.IntegerField(default=12344),
            preserve_default=False,
        ),
    ]
