# Generated by Django 4.2.2 on 2023-06-23 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_historialviajes_remove_reserva_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='asientosdisponibles',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='destino',
            field=models.CharField(default='si', max_length=120, verbose_name='Destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asientos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
