# Generated by Django 4.2.2 on 2023-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reserva_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.CharField(max_length=50),
        ),
    ]
