# Generated by Django 4.2.2 on 2023-06-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='asientos',
            field=models.IntegerField(),
        ),
    ]
